name: publish

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.PKG_REGISTRY_USERNAME}}
          password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
  build-distribution:
    name: Build distribution
    needs: build-and-push-image
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/openmcusw/bsw_code_gen:master
      credentials:
        username: ${{secrets.PKG_REGISTRY_USERNAME}}
        password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      volumes:
        - ${{github.workspace}}:/usr/project/bsw_code_gen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build dist
        run: python3 -m build --sdist --wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  publish-package:
    name: Publish package
    needs: [ build-distribution ]
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/bsw-code-gen
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish package on Python Package Index
        uses: pypa/gh-action-pypi-publish@release/v1
